### ISSUE TITLE
Clicking on Wifi icon causes segmentation fault

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#33]
https://user-images.githubusercontent.com/41370460/152931066-266ab4af-629d-465b-87b9-3e1a967e2dd2.mp4

**Comment by jmanc3** [comment]
@prateekmedia Just so you know, the Wifi menu doesn't really do much right now, even if it didn't crash. I'd like to eventually get it to talk with NetworkManager over dbus, but it looks like that is more difficult than it really should be. For now, it tries to use wpa_supplicant.

What manages Wifi connections on your system? NetworkManager, wpa_supplicant, something else entirely?

**Comment by prateekmedia** [comment]
@jmanc3 `NetworkManager` / `nmcli`

**Comment by jmanc3** [comment]
@prateekmedia I'll get on it

**Comment by D3SOX** [comment]
Also crashes for me
```
Thread 1 "winbar" received signal SIGSEGV, Segmentation fault.
0x000055555565938c in wpa_ctrl_request (ctrl=0x0, cmd=0x55555566b1a6 "LIST_NETWORKS", cmd_len=13, reply=0x7fffffffb2d0 "", reply_len=0x7fffffffac88, msg_cb=0x0) at /home/nico/building_stuff/winbar/wpa_ctrl/wpa_ctrl.c:167
167         if (send(ctrl->s, _cmd, _cmd_len, 0) < 0) {
(gdb) backtrace
#0  0x000055555565938c in wpa_ctrl_request
    (ctrl=0x0, cmd=0x55555566b1a6 "LIST_NETWORKS", cmd_len=13, reply=0x7fffffffb2d0 "", reply_len=0x7fffffffac88, msg_cb=0x0)
    at /home/nico/building_stuff/winbar/wpa_ctrl/wpa_ctrl.c:167
#1  0x000055555561d6ba in get_network_list(std::vector<ScanResult, std::allocator<ScanResult> >*) (results=0x7fffffffda20)
    at /home/nico/building_stuff/winbar/src/wifi_backend.cpp:158
#2  0x000055555561de04 in wifi_networks_and_cached_scan(void (*)(std::vector<ScanResult, std::allocator<ScanResult> >&))
    (function_called_when_results_are_returned=0x55555562278f <cached_scan_results(std::vector<ScanResult, std::allocator<ScanResult> >&)>)
    at /home/nico/building_stuff/winbar/src/wifi_backend.cpp:218
#3  0x0000555555623786 in start_wifi_menu() () at /home/nico/building_stuff/winbar/src/wifi_menu.cpp:469
#4  0x0000555555602dfa in clicked_wifi(AppClient*, cairo_t*, Container*) (client=0x55555575eb90, cr=0x555555763650, container=0x5555557ced00)
    at /home/nico/building_stuff/winbar/src/taskbar.cpp:1296
#5  0x000055555562cb0a in handle_mouse_button_release(App*) (app=0x5555557008e0) at /home/nico/building_stuff/winbar/lib/application.cpp:1430
#6  0x000055555562d3ec in handle_xcb_event(App*, unsigned int, xcb_generic_event_t*) (app=0x5555557008e0, window_number=71303183, event=0x555555969db0)
    at /home/nico/building_stuff/winbar/lib/application.cpp:1623
#7  0x000055555562d78e in handle_xcb_event(App*) (app=0x5555557008e0) at /home/nico/building_stuff/winbar/lib/application.cpp:1713
#8  0x000055555562d8f0 in xcb_poll_wakeup(App*, int) (app=0x5555557008e0, fd=3) at /home/nico/building_stuff/winbar/lib/application.cpp:1736
#9  0x000055555562db43 in app_main(App*) (app=0x5555557008e0) at /home/nico/building_stuff/winbar/lib/application.cpp:1760
#10 0x00005555555ce9cd in main() () at /home/nico/building_stuff/winbar/src/main.cpp:79
```

**Comment by jmanc3** [comment]
@D3SOX @prateekmedia does the wifi menu still segfault?

**Comment by D3SOX** [comment]
Nope, shows a warning about not being implemented now.
